default_stages: [pre-commit, pre-push, manual]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: debug-statements
      - id: no-commit-to-branch
  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: ^(fastvae/|test/)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff
        args:
          - --select=F401,F821
          - --fix
        files: ^(fastvae/|test/)
        exclude: |
          (?x)^(
          .*/__init__\.py$|
          .*\.ipynb$|
          )$
  - repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
      - id: black
        files: ^(fastvae/|test/)
  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.0
    hooks:
      - id: nbstripout
        args:
          - '--keep-output'
          - '--extra-keys=metadata.kernelspec metadata.language_info.version'
